-- phpMyAdmin SQL Dump
-- version 4.9.2
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Czas generowania: 12 Gru 2022, 14:01
-- Wersja serwera: 10.4.10-MariaDB
-- Wersja PHP: 7.3.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Baza danych: `ecommerce`
--

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `admins`
--

CREATE TABLE `admins` (
  `id` int(11) NOT NULL,
  `username` text DEFAULT NULL,
  `password` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Zrzut danych tabeli `admins`
--

INSERT INTO `admins` (`id`, `username`, `password`) VALUES
(1, 'admin', '$2y$10$IMiTgmIw5grxFJpUqVbzje9MRi0VgPmxwCJXbH4SnogjM39cHtDJO');

-- --------------------------------------------------------

--
-- Struktura tabeli dla tabeli `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `title` text DEFAULT NULL,
  `description` text DEFAULT NULL,
  `category` text DEFAULT NULL,
  `price` double DEFAULT NULL,
  `img_source` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Zrzut danych tabeli `products`
--

INSERT INTO `products` (`id`, `title`, `description`, `category`, `price`, `img_source`) VALUES
(2, 'Apple MacBook Pro 2021 14,2\"', 'Poznaj Apple MacBook Pro 2021, najnowszą odsłonę kultowego laptopa, wzbogaconą o czipy M1 Pro i M1 Max oraz technologię ProMotion. Zabierz go ze sobą do szkoły, na uczelnię czy urlop i ciesz się doskonałą jakością dźwięku i obrazu oraz niespotykaną wydajnością.', 'laptops', 2700, 'https://images.unsplash.com/photo-1526925712774-2833a7ecd0d4?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fG1hY2Jvb2t8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
(3, 'Lenovo IdeaPad Gaming 3 15IAH7 15,6\"', 'Zainstalowana fabrycznie pamięć RAM o pojemności 16 GB to gwarancja szybkiej i płynnej pracy. Bez żadnych problemów możesz uruchomić kilka aplikacji jednocześnie, ale także grać w najnowsze gry i korzystać z programów graficznych i multimediów. Wbudowany dysk półprzewodnikowy SSD jest rozwiązaniem idealnym, gdy zależy Ci na szybkości pracy komputera. Zainstalowane na nim system operacyjny i aplikacje uruchomiają się znacznie szybciej niż na dysku HDD. Dysk SSD jest o wiele bardziej wytrzymały na urazy mechaniczne a brak ruchomych części zapewnia także cichą pracę. Klawiatura z dodatkowym podświetleniem umożliwia pracę nawet w ciemnościach, bez konieczności instalowania dodatkowych źródeł światła. Proste włączanie i wyłączanie podświetlenia wpływa na wygodę i szybkość pracy na komputerze.', 'laptops', 1100, 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8bGVub3ZvJTIwbGFwdG9wfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60'),
(5, 'Apple iPhone 12 Pro 128GB', 'Prędkość 5G. A14 Bionic, ultraszybki czip napędzający iPhone’a 12. I system Pro aparatów, dzięki któremu zdjęcia w słabym świetle zyskują lepszą jakość – a iPhone 12 Pro Max jeszcze bardziej je udoskonala. Wyświetlacz Super Retina XDR sięga samych krawędzi. I ma warstwę Ceramic Shield, która czterokrotnie zwiększa odporność na upadki. Superszybka łączność bez odczuwalnych opóźnień. Możesz szybciej pobierać pliki, strumieniować wideo w wyższej jakości, cieszyć się ultrapłynną rozgrywką w grach i prowadzić interakcje w czasie rzeczywistym bez żadnych zakłóceń. Przedswiamy pierwszy w branży 5-nanometrowy czip. Szybszy, potężniejszy i wydajniejszy.', 'smartphones', 1000, 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8aXBob25lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60'),
(6, 'APPLE iPhone 13 128GB 5G 6.1\"', 'Innowacyjny system dwóch aparatów został zaaranżowany na nowo, przesuwając obiektywy o 45 stopni. Dzięki temu nowy szerokokątny obiektyw może robić jeszcze wspaniałe zdjęcia i filmy w warunkach słabego oświetlenia. Ultraszerokokątny obiektyw obejmuje szerszą ramkę, dzięki czemu uchwycisz jeszcze więcej. Od teraz możesz kręcić filmy jak zawodowi filmowcy. APPLE iPhone 13 automatycznie dostosuje przeostrzenia, zmieniając ostrość z jednego obiektu na drugi, żeby kierować uwagą widzów. Dzięki temu uzyskujemy zachwycający efekt głębi. Tryb nocny pozwoli Ci wykonać wyraźne i doświetlone zdjęcia w słabo oświetlonych sceneriach. Za pomocą trybu portretowego wyostrzony zostaje pierwszy plan, natomiast tło będzie artystycznie rozmazane. Natomiast tryb inteligentny HDR jest w stanie rozpoznać nawet cztery różne osoby w kadrze, dostosowując kontrast, a nawet odcienie skóry tak, aby wszyscy wyszli, jak najlepiej. Używając aparatu ultraszerokokątnego w iPhonie 13, masz duże pole widzenia, nawet stojąc blisko fotografowanego obiektu. Dzięki temu uchwycisz więcej, nie cofając się o krok.  Wyświetlacz Super Retina XDR jest wyraźniejszy nawet w bezpośrednim świetle słonecznym. Jasna biel, głęboka czerń i niesamowita wierność kolorów. Niezwykle wysoka gęstość pikseli zapewnia wyraźne i ostre zdjęcia i tekst. Czip A15 Bionic sprawia, że ​​wszystko działa płynniej. Obsługuje takie funkcje jak tryb filmowy, style fotograficzne i tekst na żywo. Jest bardziej ekonomiczny, dzięki czemu bateria wystarcza na dłużej. iPhone 13 to nie tylko wydajniejsza praca, ale także dłuższy czas pracy na baterii. Zyskaj nawet do 2,5 godziny więcej, używając iPhonea 13.', 'smartphones', 1300, 'https://images.unsplash.com/photo-1587831991059-40958cea9ca5?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fGlwaG9uZXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(7, 'SAMSUNG Galaxy S22 8/128GB 5G 6.1\"', 'Aparat główny o rozdzielczości 50 MP pozwala nawet po zmierzchu rejestrować prawidłowo doświetlone, kontrastowe oraz pełne kolorów zdjęcia i filmy. Bateria ma pojemność 3700 mAh. Bateria wspiera szybkie ładowanie 25 W, co umożliwia dłuższe korzystanie ze smartfona. Niezwykłe płynne działanie bez opóźnień nawet podczas zaawansowanych rozgrywek 3D dzięki procesorowi wykonanemu w technologii 4 nm. Smartfon łączy w sobie nowoczesny design, stylowe kolory oraz najwyższą wytrzymałość. Wszystkie urządzenia Galaxy, które posiadasz współpracują ze sobą, podnosząc komfort ich użytkowania.', 'smartphones', 850, 'https://images.unsplash.com/photo-1566837539809-c2ed29eeea08?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fHNhbXN1bmclMjBzbWFydHBob25lfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60'),
(8, 'HUAWEI P50 Pro 8/256GB 6.6\"', 'Seria HUAWEI P od momentu powstania stanowi idealne połączenie technologii, estetyki i inteligentnej fotografii. Modele z tej serii wyróżnia wyjątkowa dbałość o jakość, styl, a także szczyt innowacji w zakresie fotografii mobilnej. Tak też jest w przypadku HUAWEI P50 Pro, który dzięki podwójnemu modułowi fotograficznemu Dual Matrix Camera i technologii True-Chroma odkrywa esencję fotografii i artyzm wykonanych zdjęć. Ten flagowiec jest wyposażony w większy, 6,6-calowy ekran i wydajniejszą 4360 mAh baterię, a jednocześnie jest lżejszy i smuklejszy od poprzednika. Dzięki częstotliwości odświeżania ekranu do 120 Hz i częstotliwości próbkowania dotykowego 300 Hz użytkownicy mogą cieszyć się niezakłóconym, płynnym obrazem. Dodatkowo interfejs EMUI 12 wnosi jeszcze więcej inteligentnych rozwiązań. Jest też odporny na wodę i pył dzięki klasie szczelności IP68. HUAWEI P50 Pro ma większy wyświetlacz oraz baterię, a jednocześnie pozostaje smukły, lekki i wygodny do trzymania w dłoni. Znakomite wzornictwo sprawia, że wydaje się on jeszcze lżejszy niż w rzeczywistości i wygodniej leży w dłoni. Zakrzywiony 6,6-calowy wyświetlacz OLED, pojemna bateria 4360 mAh oraz dwa głośniki z dźwiękiem przestrzennym i mocnym basem zostały zamknięte w wyjątkowo kompaktowej konstrukcji o grubość 8,5 mm i wadze ok. 195 g. HUAWEI P50 Pro wspiera superszybkie ładowanie przewodowe (66 W SuperCharge) oraz bezprzewodowe (50 W SuperCharge). Zasilany pojemną baterią i napędzany procesorem Snapdragon 888 w połączeniu z innowacyjnym oprogramowaniem EMUI 12 zapewni Ci moc wyjątkowych wrażeń. HUAWEI zawsze dążył do osiągnięcia najlepszej w swojej klasie technologii zdjęć i jakości obrazu. Dlatego też flagowiec HUAWEI P50 Pro zapewnia udoskonalone, profesjonalne wrażenia dzięki podwójnemu modułowi fotograficznemu, optyce HUAWEI XD oraz technologii True-Chroma. Najnowszy system aparatów Dual-Matrix Camera w HUAWEI P50 Pro składa się z aparatu głównego 50 MP, aparatu monochromatycznego 40 MP, aparatu 13 MP z obiektywem ultraszerokokątnym oraz aparatu 64 MP z teleobiektywem. Równoważąc możliwości wielu obiektywów, 10-kanałowego czujnika wielospektralnego, optyki HUAWEI XD, procesora obrazu XD Fusion Pro i innych innowacji, HUAWEI P50 Pro oferuje niesamowite możliwości fotografowania, z niezwykłą wyrazistością każdego detalu, szerokim zakresem tonalnym i doskonałym odwzorowaniem kolorów.', 'smartphones', 900, 'https://images.unsplash.com/photo-1541345023926-55d6e0853f4b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTJ8fGh1YXdlaSUyMHNtYXJ0cGhvbmV8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
(9, 'Słuchawki nauszne SONY WH-1000XM5B ANC', 'Przedstawiamy SONY WH-1000XM5, które spełnią oczekiwania nie jednego użytkownika! Rozbudowane technologie, redukcje szumów, wyjątkowy dźwięk i nie tylko. Przekonaj się! Każdy nausznik słuchawek został wyposażony w cztery mikrofony z redukcją szumów. Zmniejsz hałas dobiegający z zewnątrz i zadbaj o czysty dźwięk. Jest to technologia, dzięki której na bieżąco zredukowany zostaje hałas. Nowy zintegrowany procesor V1 pozwoli na uwolnienie potencjału QN1 HD – czyli nowego systemu. Dzięki temu połączeniu możesz być pewien, że system kontrolujący nie zawiedzie. SONY WH-1000XM5 mają 30-milimetrowe przetworniki, które zostały wykonane z miękką krawędzią z TPU, co wpływa na redukcję szumów. Membrana jest lekka i sztywna, dzięki czemu dźwięk dostający się do ucha, będzie czysty, a basy będą wyraźne. Dzięki naszej uznanej bezprzewodowej technologii kodowania dźwięku LDAC słuchawki Sony z redukcją szumów obsługują dźwięk High-Resolution Audio i bezprzewodowy dźwięk High-Resolution Audio Wireless. LDAC przesyła prawie trzykrotnie więcej danych niż tradycyjne kodeki Bluetooth, oczywiście nie zagrażając jakości dźwięku! WH-1000XM5 oferuje również najlepszą jakość połączeń. Sztuczna inteligencja wykorzystująca cztery mikrofony oraz algorytmy redukcji szumów izoluje Twój głos. Dodatkowo nowo opracowana struktura redukcji szumu wiatru zminimalizuje niechciane dźwięki. Bądź pewien, że Twój rozmówca słyszy Cię wyraźnie. Inteligentna funkcja adaptacyjnej kontroli dźwięku zapewnia doskonałe wrażenia słuchowe dzięki temu, że wykrywa, gdzie się znajdujesz i automatycznie dopasowuje ustawienia do dźwięków otoczenia. Technologia zapamiętuje Twoje zwyczaje i zapamiętuje miejsca, w których często bywasz, np. pracę albo ulubioną knajpę. Kiedy zaczniesz rozmowę, funkcja Mów do czatu wstrzyma muzykę i pozwoli Ci rozmawiać przez słuchawki, zupełnie bez użycia rąk, a kiedy skończysz rozmawiać, muzyka zostanie wznowiona. Zapewnia to wbudowany mikrofon zestawu słuchawkowego i zaawansowane przetwarzanie sygnału audio, które nie tylko rozpoznaje głos, ale też reaguje na niego. Czujniki pojemnościowe odczytują, kiedy masz słuchawki na sobie i pauzują muzykę, kiedy je zdejmujesz, a wznawiają, kiedy ponownie je założysz.', 'headphones', 450, 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8aGVhZHBob25lc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(10, 'Słuchawki nauszne BEATS BY DR. DRE Solo 3 Wireless', 'Wydajność baterii słuchawek bezprzewodowych Beats Solo 3 Wireless sięga nawet do 40 godzin, co czyni z nich idealny sprzęt muzyczny na co dzień. 5 minutowe ładowanie w trybie Fast Fuel wystarcza do 3 godzin grania. Słuchawki charakteryzują się wyjątkowym, wielokrotnie nagradzanym brzmieniem i dają pełną swobodę dzięki bezprzewodowej technologii Bluetooth klasy 1. A możliwość regulacji nausznych muszli z miękką wyściółką zapewnia pełen komfort noszenia. Energooszczędny czip W1 płynnie obsługuje podłączanie i przełączanie urządzeń Apple*, pobiera tak małą moc, że akumulator słuchawek wystarczy nawet na 40 godzin odtwarzania, a system Fast Fuel w ciągu 5 minut ładuje słuchawki energią potrzebną na 3 godziny grania. Słuchawki bezprzewodowe Beats Solo 3 Wireless są zawsze gotowe do akcji. Ich konfiguracja jest błyskawiczna – wystarczy, że je włączysz i zbliżysz do iPhone’a, aby jednocześnie połączyły się ze wszystkimi Twoimi urządzeniami: zegarkiem Apple Watch, iPadem i komputerem Mac. Czip Apple W1 obsługuje łączność Bluetooth klasy 1 – to najwyższy możliwy wynik, jeśli chodzi o zasięg i siłę sygnału. Dzięki najlepszej w swojej klasie technologii parowania słuchawki bezproblemowo synchronizują się z Twoimi urządzeniami. Możesz więc swobodnie się poruszać i stale słuchać swojej ulubionej muzyki. *Wymagane jest konto w iCloud i system macOS Sierra, iOS 10, watchOS 3 lub nowsze wersje tych systemów. Najważniejszą cechą słuchawek Beats Solo 3 Wireless jest pierwszorzędne brzmienie Beats. Dopracowany w najdrobniejszych szczegółach układ akustyczny gwarantuje czysty, zrównoważony dźwięk w szerokim zakresie częstotliwości. Komfortowo wyściełane muszle tłumią szumy otoczenia i przenoszą bogactwo tonów, pozwalając Ci słuchać muzyki dokładnie tak, jak została nagrana. Słuchawki nauszne BEATS BY DR. DRE Solo 3 Wireless Czerwony - komfort', 'headphones', 299, 'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fGhlYWRwaG9uZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
(11, 'Słuchawki dokanałowe APPLE AirPods Pro ANC', 'Chcesz, aby Twoje nowe słuchawki były niezawodne? AirPods PRO to bezprzewodowe słuchawki dokanałowe. Będą towarzyszyć Ci podczas Twoich zmagań z codziennością bez najmniejszych problemów! Ich waga to niewiele ponad 4 gramy tak więc sprawią, że poczujesz się komfortowo! Wykonane z najwyższą starannością słuchawki zamknięte w białej obudowie. Lubisz słuchać muzyki, podcastów? Apple daje Ci możliwość spełniania swoich wymagań z AirPods PRO! Dźwięk przestrzenny z dynamicznym śledzeniem ruchu głowy sprawi, że wszystkie dźwięki docierają do Ciebie bez problemu! Słuchanie muzyki w słuchawkach AirPods PRO to czysta przyjemność! Niechciane dźwięku z otoczenia są idealnie tłumione dzięki aktywnej redukcji szumu. Skup się na tym co ważne! Dźwięki, które słyszysz w słuchawce, automatycznie dopasowują się do kształtu Twojego ucha. Mikrofon skierowany do wewnątrz wychwytuje dźwięk, a następnie dostosowuje niskie i średnie częstotliwości. To zawdzięczysz adaptacyjnej korekcji – EQ. Żaden szczegół Ci nie umknie! Wbudowana technologia Bluetooth 5.0 w AirPods PRO ma za zadanie ułatwić Ci codzienne funkcjonowanie. Wyjmij je z etui, sparuj z urządzeniem i ciesz się nieograniczonymi możliwościami! Łączność bezprzewodowa to brak plączących się kabli! Na pewno to docenisz podczas uprawiania sportu i nie tylko! Nie obawiaj się deszczu i intensywnego treningu. Klasa odporności IPX4 zapewnia pełen komfort Tobie! Boisz się o to, że pod wpływem kontaktu z wodą przestaną działać? Nie ma takiej możliwości! Etui ładujące MagSafe także posiada tę klasę odporności.', 'headphones', 399, 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YWlycG9kc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(12, 'Słuchawki dokanałowe APPLE AirPods Pro II', 'Nowy, zaprojektowany przez APPLE układ H2 jest siłą napędową słuchawek AirPods Pro i ich zaawansowanej wydajności audio. Współpracuje z niestandardowym przetwornikiem i wzmacniaczem, aby zapewnić wyraźne, czyste wysokie tony i głębokie, bogate basy w oszałamiającej rozdzielczości — dzięki czemu każdy dźwięk jest żywszy. Zupełnie nowy chip H2 zapewnia więcej funkcji niż kiedykolwiek, wykorzystując algorytmy obliczeniowe, aby zapewnić jeszcze inteligentniejszą redukcję szumów, doskonały trójwymiarowy dźwięk i dłuższą żywotność baterii — wszystko naraz. Chip wykorzystuje potężne nowe algorytmy adaptacyjne, aby szybciej przetwarzać dźwięk, dostrajając dźwięk dokładnie w momencie, gdy go słyszysz. Każdy szczegół jest renderowany dla konkretnego kształtu ucha, zanurzając Cię w dźwięku o większej wierności. Niestandardowy przetwornik i wzmacniacz współpracują z układem H2, aby zapewnić mniejsze zniekształcenia podczas odtwarzania, dzięki czemu usłyszysz głębsze basy i wyraźniejsze tony wysokie — na wszystkich poziomach głośności. Mikrofony z redukcją szumów i tylny otwór wentylacyjny są optymalnie rozmieszczone, aby szybko wykrywać dochodzący dźwięk i współpracują ze sobą, aby przeciwdziałać hałasowi, zanim dotrze on do ucha. Do zestawu dołączone są cztery pary silikonowych wkładek, w tym także w rozmiarze XS, które pasują do szerszego zakresu uszu. Wkładki dokładnie dopasowują się do uszu, tworząc doskonale izolowaną przestrzeń dla dźwięku i chronią AirPods Pro przed wypadaniem. Sterowanie dotykowe pozwala łatwo zarządzać funkcjami odtwarzania ze słuchawki. Przesuń palcem w górę lub w dół, aby dostosować głośność, naciśnij, aby odtwarzać i wstrzymywać muzykę lub odbierać i kończyć połączenia lub przytrzymaj, aby przełączać się między aktywną redukcją szumów a adaptacyjnym trybem kontaktu.', 'headphones', 449, 'https://images.unsplash.com/photo-1605464315542-bda3e2f4e605?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8YWlycG9kc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(13, 'Etui na słuchawki do Apple AirPods Pro 1 gen/2 gen', 'Silikonowe etui ochronne marki Hama kompatybilne z etui ładującym do Apple AirPods Pro. Posiada wycięcie diody LED, która sygnalizuje naładowanie słuchawek.', 'accessories', 15, 'https://images.unsplash.com/photo-1601592908805-7513f10bb3e3?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjN8fGVsZWN0cm9uaWMlMjBhY2Nlc3Nvcmllc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(14, 'Drewniany stojak na telefon', 'Jest to piękny stojak na telefon komórkowy. Wykonane z najwyższej jakości materiału i to drewno, te stojaki są bardzo trwałe w użytkowaniu. Kształt kreskówki sprawia, że te uchwyty na telefony komórkowe są piękne i niepowtarzalne. Nadaje się do domu, gabinetu, biura, sypialni i innych potrzebnych miejsc. umieść telefon poziomo lub pionowo. Świetny prezent! Pamiątki z drewna pod zamówienie na indywidualne zamówienie.', 'accessories', 10, 'https://images.unsplash.com/photo-1521120413309-42e7eada0334?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjh8fGVsZWN0cm9uaWMlMjBhY2Nlc3Nvcmllc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(15, 'Lokalizator Apple AirTag 1', 'Apple AirTag to niewielkich rozmiarów lokalizator przedmiotów, który pomoże Ci łatwiej nad nimi zapanować. Kompaktowa konstrukcja przedmiotu pozwoli Ci przymocować go do kluczy lub schować do plecaka. To wszystko. Od tej chwili Twoje przedmioty ukażą się na radarze w aplikacji Lokalizator, za pomocą której możesz także śledzić Twoje urządzenia od firmy Apple. Nie obawiaj się, że zgubisz swój portfel, ponieważ lokalizator Apple AirTag pomoże Ci go odnaleźć. Nawet jeśli zostawisz coś w oddalonym od Ciebie miejscu, w znalezieniu Twojego przedmiotu pomoże sieć usługi Znajdź mój, w skład której wchodzą setki milionów telefonów iPhone, tabletów iPad i komputerów Mac. Apple AirTag działa ponad rok na zwykłej baterii, którą łatwo wymienisz. iPhone poinformuje Cię, kiedy to zrobić. W przypadku kiedy zgubisz przedmiot z przyczepionym do niego lokalizatorem Apple AirTag nie musisz panikować. Wystarczy, że otworzysz aplikację Lokalizator na swoim urządzeniu od firmy Apple i przejdziesz do nowej karty Rzeczy. Po odnalezieniu na liście zgubionego przedmiotu wystarczy, że włączysz dźwięk na wbudowanym w AirTag głośniku. Jeśli przedmiot znajduje się blisko Ciebie usłyszysz sygnał dźwiękowy, który bezbłędnie poprowadzi Cię do Twojej zguby. Co więcej, jeśli lokalizator Apple AirTag jest w pobliżu, Twój iPhone doprowadzi Cię prosto do niego za pomocą funkcji Znajdowanie dokładne*. Technologia Ultra Wideband pozwoli Ci zobaczyć, w jakiej odległości i w którym kierunku powinieneś szukać. *Funkcja Znajdowanie dokładne działa na następujących urządzeniach: iPhone 11, iPhone 11 Pro, iPhone 11 Pro Max, iPhone 12, iPhone 12 mini, iPhone 12 Pro, iPhone 12 Pro Max, iPhone 13, iPhone 13 mini, iPhone 13 Pro, iPhone 13 Pro Max, iPhone 14, iPhone 14 Plus, iPhone 14 Pro i iPhone 14 Pro Max.', 'accessories', 49, 'https://images.unsplash.com/photo-1620376153436-02f9a4b44d88?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8ODN8fGVsZWN0cm9uaWMlMjBhY2Nlc3Nvcmllc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60'),
(16, 'Etui APPLE Clear Case MagSafe do iPhone 14', 'Smukłe, lekkie i świetnie leżące w dłoni etui Apple chroni iPhone’a 14, nie zasłaniając pięknej, kolorowej obudowy. Zastosowanie mieszanki przezroczystego poliwęglanu i elastycznych materiałów pozwoliło na dokładne dopasowanie kształtu do przycisków, żeby wygodnie się ich używało. Odporna na zadrapania powłoka pokrywa zarówno zewnętrzną, jak i wewnętrzną powierzchnię etui. Wszystkie materiały i powłoki są też optymalnie zabezpieczone przed żółknięciem. Wbudowane magnesy, które za każdym razem precyzyjnie dopasowują etui do iPhone’a 14, sprawiają, że ładowanie jest szybsze, a inne akcesoria przyłączają się i odłączają niemal magicznie. Etui nie trzeba zdejmować do ładowania. Wystarczy doczepić ładowarkę MagSafe lub położyć iPhone’a na ładowarce z certyfikatem Qi. To etui, jak każde zaprojektowane przez Apple, przeszło tysiące godzin testów na wszystkich etapach projektowania i produkcji. Dzięki temu nie tylko świetnie wygląda, ale też skutecznie chroni iPhone’a przed uderzeniami i zadrapaniami.', 'accessories', 12, 'https://images.unsplash.com/photo-1594843665794-446ce915d840?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTMxfHxlbGVjdHJvbmljJTIwYWNjZXNzb3JpZXN8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60'),
(17, 'Laptop ASUS Vivobook Pro 15 K3500PC-KJ200W 15,6\"', 'Trio najważniejszych podzespołów? Procesor, karta graficzna i pamięć. W każdej z tych kategorii VivoBook Pro 15 zgarnia wysokie noty. Napędza go procesor Intel® Core™. Karta graficzna NVIDIA® GeForce RTX™ zapewnia obsługę ray tracingu i wykorzystuje potencjał sztucznej inteligencji. Masz do dyspozycji więcej niż wystarczającą ilość pamięci RAM. Co to oznacza? VivoBook Pro 15 sprosta wszystkim wyzwaniom, które postawią przed nim gracze czy profesjonalni twórcy. Taka specyfikacja umożliwia swobodną pracę w programach graficznych, szybkie renderowanie i edycję wideo oraz dynamiczną rozgrywkę na najwyższym poziomie.', 'laptops', 1300, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8bGVub3ZvJTIwbGFwdG9wfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60');

--
-- Indeksy dla zrzutów tabel
--

--
-- Indeksy dla tabeli `admins`
--
ALTER TABLE `admins`
  ADD PRIMARY KEY (`id`);

--
-- Indeksy dla tabeli `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT dla tabel zrzutów
--

--
-- AUTO_INCREMENT dla tabeli `admins`
--
ALTER TABLE `admins`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT dla tabeli `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=18;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
